set -e
<<<<<<< HEAD
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/fixmatch/fixmatch_cifar10_250_0.yaml --save_name determine --prefix fixmatch-ours_cifar10_0_0.001 --gpu 0 --seed 0 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.001 --post_hoc_max_epochs 100 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 1000 --n_cal 1000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/fixmatch/fixmatch_cifar10_250_0.yaml --save_name determine --prefix fixmatch-ours_cifar10_0_0.005 --gpu 0 --seed 0 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.005 --post_hoc_max_epochs 100 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 1000 --n_cal 1000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/fixmatch/fixmatch_cifar10_250_0.yaml --save_name determine --prefix fixmatch-ours_cifar10_1_0.001 --gpu 0 --seed 1 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.001 --post_hoc_max_epochs 100 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 1000 --n_cal 1000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/fixmatch/fixmatch_cifar10_250_0.yaml --save_name determine --prefix fixmatch-ours_cifar10_1_0.005 --gpu 0 --seed 1 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.005 --post_hoc_max_epochs 100 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 1000 --n_cal 1000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/fixmatch/fixmatch_cifar10_250_0.yaml --save_name determine --prefix fixmatch-ours_cifar10_2_0.001 --gpu 0 --seed 2 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.001 --post_hoc_max_epochs 100 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 1000 --n_cal 1000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/fixmatch/fixmatch_cifar10_250_0.yaml --save_name determine --prefix fixmatch-ours_cifar10_2_0.005 --gpu 0 --seed 2 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.005 --post_hoc_max_epochs 100 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 1000 --n_cal 1000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/freematch/freematch_cifar10_250_0.yaml --save_name determine --prefix freematch-ours_cifar10_0_0.001 --gpu 0 --seed 0 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.001 --post_hoc_max_epochs 100 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 1000 --n_cal 1000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/freematch/freematch_cifar10_250_0.yaml --save_name determine --prefix freematch-ours_cifar10_0_0.005 --gpu 0 --seed 0 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.005 --post_hoc_max_epochs 100 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 1000 --n_cal 1000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/freematch/freematch_cifar10_250_0.yaml --save_name determine --prefix freematch-ours_cifar10_1_0.001 --gpu 0 --seed 1 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.001 --post_hoc_max_epochs 100 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 1000 --n_cal 1000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/freematch/freematch_cifar10_250_0.yaml --save_name determine --prefix freematch-ours_cifar10_1_0.005 --gpu 0 --seed 1 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.005 --post_hoc_max_epochs 100 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 1000 --n_cal 1000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/freematch/freematch_cifar10_250_0.yaml --save_name determine --prefix freematch-ours_cifar10_2_0.001 --gpu 0 --seed 2 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.001 --post_hoc_max_epochs 100 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 1000 --n_cal 1000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/freematch/freematch_cifar10_250_0.yaml --save_name determine --prefix freematch-ours_cifar10_2_0.005 --gpu 0 --seed 2 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.005 --post_hoc_max_epochs 100 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 1000 --n_cal 1000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/fixmatch/fixmatch_cifar100_2500_0.yaml --save_name determine --prefix fixmatch-ours_cifar100_0_0.001 --gpu 0 --seed 0 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.001 --post_hoc_max_epochs 500 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 3000 --n_cal 3000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/fixmatch/fixmatch_cifar100_2500_0.yaml --save_name determine --prefix fixmatch-ours_cifar100_0_0.005 --gpu 0 --seed 0 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.005 --post_hoc_max_epochs 500 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 3000 --n_cal 3000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/fixmatch/fixmatch_cifar100_2500_0.yaml --save_name determine --prefix fixmatch-ours_cifar100_1_0.001 --gpu 0 --seed 1 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.001 --post_hoc_max_epochs 500 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 3000 --n_cal 3000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/fixmatch/fixmatch_cifar100_2500_0.yaml --save_name determine --prefix fixmatch-ours_cifar100_1_0.005 --gpu 0 --seed 1 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.005 --post_hoc_max_epochs 500 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 3000 --n_cal 3000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/fixmatch/fixmatch_cifar100_2500_0.yaml --save_name determine --prefix fixmatch-ours_cifar100_2_0.001 --gpu 0 --seed 2 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.001 --post_hoc_max_epochs 500 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 3000 --n_cal 3000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/fixmatch/fixmatch_cifar100_2500_0.yaml --save_name determine --prefix fixmatch-ours_cifar100_2_0.005 --gpu 0 --seed 2 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.005 --post_hoc_max_epochs 500 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 3000 --n_cal 3000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/freematch/freematch_cifar100_2500_0.yaml --save_name determine --prefix freematch-ours_cifar100_0_0.001 --gpu 0 --seed 0 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.001 --post_hoc_max_epochs 500 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 3000 --n_cal 3000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/freematch/freematch_cifar100_2500_0.yaml --save_name determine --prefix freematch-ours_cifar100_0_0.005 --gpu 0 --seed 0 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.005 --post_hoc_max_epochs 500 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 3000 --n_cal 3000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/freematch/freematch_cifar100_2500_0.yaml --save_name determine --prefix freematch-ours_cifar100_1_0.001 --gpu 0 --seed 1 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.001 --post_hoc_max_epochs 500 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 3000 --n_cal 3000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/freematch/freematch_cifar100_2500_0.yaml --save_name determine --prefix freematch-ours_cifar100_1_0.005 --gpu 0 --seed 1 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.005 --post_hoc_max_epochs 500 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 3000 --n_cal 3000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/freematch/freematch_cifar100_2500_0.yaml --save_name determine --prefix freematch-ours_cifar100_2_0.001 --gpu 0 --seed 2 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.001 --post_hoc_max_epochs 500 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 3000 --n_cal 3000
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/freematch/freematch_cifar100_2500_0.yaml --save_name determine --prefix freematch-ours_cifar100_2_0.005 --gpu 0 --seed 2 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps 0.005 --post_hoc_max_epochs 500 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 3000 --n_cal 3000
=======
OPT_TH=YES MODEL_SELECTION=Cov python3 train.py --c config/classic_cv/fixmatch/fixmatch_cifar10_250_0.yaml --save_name determine --prefix fixmatch-ours_cifar10_0_schedule-1 --gpu 0 --seed 0 --epoch 1000 --num_train_iter 25000 --should_use_cache True --accumulate_pseudo_labels True --use_post_hoc_calib True --full_pl_flag True --batch_pl_flag False --save_dir saved_models --post_hoc_eps schedule-1 --post_hoc_max_epochs 100 --mr False --mr_config ./config/mr/default.yaml --bam False --bam_config ./config/bam/default.yaml --take_d_cal_th_from eval --n_th 1000 --n_cal 1000 --full_pl_freq 1
>>>>>>> 0bd54894c3e52fe4ec896b71bb415c06c029e069
